### ISSUE TITLE
`issues list` throws Error when issue body is empty 

### ISSUE THREAD

**Issue by Adamih** [repobee/repobee#1013]
The command throws when there is an issue with only a title. 

Console log:

```
$ python3 src/repobee.py issues list --show-body -a template-task-1 --title-regex ".*"

[ERROR] AttributeError: 'NoneType' object has no attribute 'split'
[ERROR] Critical exception
Traceback (most recent call last):
  File "/Users/zinokader/Documents/Skoldokument/Datalogi/SoftwareFundamentals/repobee/src/_repobee/main.py", line 236, in _core_error_handler
    yield
  File "/Users/zinokader/Documents/Skoldokument/Datalogi/SoftwareFundamentals/repobee/src/_repobee/main.py", line 182, in _run_cli
    _repobee.cli.dispatch.dispatch_command(
  File "/Users/zinokader/Documents/Skoldokument/Datalogi/SoftwareFundamentals/repobee/src/_repobee/cli/dispatch.py", line 39, in dispatch_command
    else _dispatch_legacy_command(args, config, api)
  File "/Users/zinokader/Documents/Skoldokument/Datalogi/SoftwareFundamentals/repobee/src/_repobee/cli/dispatch.py", line 57, in _dispatch_legacy_command
    return dispatch_table[args.category](args, config, api) or {}
  File "/Users/zinokader/Documents/Skoldokument/Datalogi/SoftwareFundamentals/repobee/src/_repobee/cli/dispatch.py", line 126, in _dispatch_issues_command
    return command.list_issues(
  File "/Users/zinokader/Documents/Skoldokument/Datalogi/SoftwareFundamentals/repobee/src/_repobee/command/issues.py", line 73, in list_issues
    pers_issues_per_repo = _log_repo_issues(
  File "/Users/zinokader/Documents/Skoldokument/Datalogi/SoftwareFundamentals/repobee/src/_repobee/command/issues.py", line 179, in _log_repo_issues
    out += os.linesep * 2 + _limit_line_length(issue.body)
  File "/Users/zinokader/Documents/Skoldokument/Datalogi/SoftwareFundamentals/repobee/src/_repobee/command/issues.py", line 194, in _limit_line_length
    lines = s.split(os.linesep)
AttributeError: 'NoneType' object has no attribute 'split'
[ERROR] RepoBee exited unexpectedly. Please visit the FAQ to try to resolve the problem: https://repobee.readthedocs.io/en/stable/faq.html
```

**Comment by slarse** [comment]
So I'm guessing PyGitHub returns `None` for the body of an issue with an empty body. The fix would be rather straightforward here:

https://github.com/repobee/repobee/blob/2c9b5a8dac3c228e8722ed9111e9064914d4c3fc/src/_repobee/ext/defaults/github.py#L334-L344

I'm thinking this should work:

```diff
-               body=issue.body,
+               body=issue.body or "",
```

Could you try that and see if it works for you?

**Comment by Adamih** [comment]
Fix works fantastically, will submit PR.

**Comment by ZinoKader** [comment]
Seemed to only happen with the `--show-body` flag, which I guess is why it slipped through the cracks.
