### ISSUE TITLE
Critical error running juni4 hooks

### ISSUE THREAD

**Issue by Karlkorv** [repobee/repobee#1077]
When running `repobee repos clone` with the `junit` and `javac` hooks I get the following error:

```
Executing post_clone hooks:  47%|███████▍        | 7/15 [00:04<00:05,  1.52it/s][ERROR] critical
Traceback (most recent call last):
  File "/Users/janneschyffert/.repobee/env/lib/python3.10/site-packages/repobee_junit4/junit4.py", line 132, in post_clone
    compile_succeeded, compile_failed = self._compile_all(repo)
  File "/Users/janneschyffert/.repobee/env/lib/python3.10/site-packages/repobee_junit4/junit4.py", line 179, in _compile_all
    compile_succeeded, compile_failed = _java.pairwise_compile(
  File "/Users/janneschyffert/.repobee/env/lib/python3.10/site-packages/repobee_junit4/_java.py", line 194, in pairwise_compile
    status, msg, prod_class_path = _pairwise_compile(
  File "/Users/janneschyffert/.repobee/env/lib/python3.10/site-packages/repobee_junit4/_java.py", line 275, in _pairwise_compile
    potential_prod_classes = _get_matching_prod_classes(
  File "/Users/janneschyffert/.repobee/env/lib/python3.10/site-packages/repobee_junit4/_java.py", line 310, in _get_matching_prod_classes
    return [
  File "/Users/janneschyffert/.repobee/env/lib/python3.10/site-packages/repobee_junit4/_java.py", line 313, in <listcomp>
    if file.name == prod_class_name and extract_package(file) == package
  File "/Users/janneschyffert/.repobee/env/lib/python3.10/site-packages/repobee_junit4/_java.py", line 84, in extract_package
    with class_.open(encoding=sys.getdefaultencoding(), mode="r") as file:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 1117, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
IsADirectoryError: [Errno 21] Is a directory: '/var/folders/9k/5mkds41d7qvcd95xrb72xbt40000gn/T/tmpa4_0e6lo/947c16c3f94945663c0b4c0fa20f9a8929fb8cf9/src/Indamon.java'
Executing post_clone hooks: 100%|███████████████| 15/15 [00:08<00:00,  1.68it/s]
```

The hooks run regardless and seem to be working correctly despite the error. This is my repobee-config:
```
[repobee]
user = jannesc
token = xxxxxxxxxx
students_file = /Users/janneschyffert/Documents/INDA-TA/students.txt

[junit4]
junit4_reference_tests_dir = /Users/janneschyffert/Documents/INDA-TA/test-files
junit4_hamcrest_path = /Users/janneschyffert/Documents/INDA-TA/test-jars/hamcrest-core-1.3.jar
junit4_junit_path = /Users/janneschyffert/Documents/INDA-TA/test-jars/junit-4.13.1.jar
junit4_timeout = 5
```

**Comment by slarse** [comment]
Hi @Karlkorv,

At a glance, it looks like a student has a _directory_ called Indamon.java in their repository. It appears as if the JUnit4 plugin just assumes that any path with a `.java` suffix is a normal file, which doesn't hold in this situation (https://github.com/repobee/repobee-junit4/blob/e80a720f6830f7a0038959526d548648b932f3d6/repobee_junit4/_java.py#L84-L86).
I'll get around to patching that during the weekend, then you'll need to upgrade your version of the JUnit4 plugin :)
