### ISSUE TITLE
Issues with fine-tokens

### ISSUE THREAD

**Issue by EdgyGuy19** [repobee/repobee#1266]
During repobee config verify the fine-token on github causes errors. Everything works fine with classic ones.

**Comment by rjglasse** [comment]
I repeated this bug with the new tokens. Here is the trace:

```bash
% repobee config verify 
Verifying settings ...
Trying to fetch user information ...
SUCCESS: found user glassey, user exists and base url looks okay
Verifying access token scopes ...
[ERROR] AssertionError: 
[ERROR] Critical exception
Traceback (most recent call last):
  File "/Users/ric/.repobee/env/lib/python3.9/site-packages/_repobee/main.py", line 236, in _core_error_handler
    yield
  File "/Users/ric/.repobee/env/lib/python3.9/site-packages/_repobee/main.py", line 182, in _run_cli
    _repobee.cli.dispatch.dispatch_command(
  File "/Users/ric/.repobee/env/lib/python3.9/site-packages/_repobee/cli/dispatch.py", line 56, in dispatch_command
    dispatch_table[category](args, config, api) or hook_results
  File "/Users/ric/.repobee/env/lib/python3.9/site-packages/_repobee/cli/dispatch.py", line 141, in _dispatch_config_command
    plug.manager.hook.get_api_class().verify_settings(
  File "/Users/ric/.repobee/env/lib/python3.9/site-packages/_repobee/ext/defaults/github.py", line 488, in verify_settings
    assert scopes is not None
AssertionError
[ERROR] RepoBee exited unexpectedly. Please visit the FAQ to try to resolve the problem: https://repobee.readthedocs.io/en/stable/faq.html
```
