### ISSUE TITLE
Crash in list-issues command

### ISSUE THREAD

**Issue by slarse** [repobee/repobee#253]
Traceback:

```
[ERROR] 'Issue' object has no attribute 'user'
[ERROR] critical exception
Traceback (most recent call last):
  File "/home/slarse/.local/lib/python3.7/site-packages/repobee/main.py", line 66, in main
    cli.dispatch_command(parsed_args, api)
  File "/home/slarse/.local/lib/python3.7/site-packages/repobee/cli.py", line 303, in dispatch_command
    author=args.author,
  File "/home/slarse/.local/lib/python3.7/site-packages/repobee/command.py", line 235, in list_issues
    _log_repo_issues(issues_per_repo, show_body, max_repo_name_length + 6)
  File "/home/slarse/.local/lib/python3.7/site-packages/repobee/command.py", line 274, in _log_repo_issues
    issue.user.login,
AttributeError: 'Issue' object has no attribute 'user'
```

**Comment by slarse** [comment]
probably some bleedthrough from PyGithub, before switching to the platform independent classes
