### ISSUE TITLE
GitLab plugin crashes unexpectedly when specifying non-existent master/target group

### ISSUE THREAD

**Issue by slarse** [repobee/repobee#422]
If the target or master orgs don't actually exist, the GitLab plugin crashes with an IndexError. Trace:

```
[ERROR] a IndexError occured unexpectedly: list index out of range
[INFO] exception was raised before pre-initialization was complete. This is usually due to incorrect settings. Try running the `verify-settings` command and see if the problem can be resolved. If all fails, please open an issue at https://github.com/repobee/repobee/issues/new and supply the stack trace below.
[ERROR] Critical exception
Traceback (most recent call last):
  File "/home/slarse/.local/lib/python3.8/site-packages/_repobee/ext/gitlab.py", line 80, in _try_api_request
    yield
  File "/home/slarse/.local/lib/python3.8/site-packages/_repobee/ext/gitlab.py", line 116, in __init__
    self._group = self._get_organization(self._group_name)
  File "/home/slarse/.local/lib/python3.8/site-packages/_repobee/ext/gitlab.py", line 201, in _get_organization
    return [
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/slarse/.local/lib/python3.8/site-packages/_repobee/main.py", line 63, in main
    parsed_args, api = _repobee.cli.parsing.handle_args(
  File "/home/slarse/.local/lib/python3.8/site-packages/_repobee/cli/parsing.py", line 67, in handle_args
    processed_args, api = _process_args(args, ext_commands)
  File "/home/slarse/.local/lib/python3.8/site-packages/_repobee/cli/parsing.py", line 149, in _process_args
    api = _connect_to_api(args.base_url, args.token, args.org_name, args.user)
  File "/home/slarse/.local/lib/python3.8/site-packages/_repobee/cli/parsing.py", line 290, in _connect_to_api
    return api_class(**kwargs)
  File "/home/slarse/.local/lib/python3.8/site-packages/_repobee/ext/gitlab.py", line 116, in __init__
    self._group = self._get_organization(self._group_name)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/slarse/.local/lib/python3.8/site-packages/_repobee/ext/gitlab.py", line 95, in _try_api_request
    raise exception.UnexpectedException(
_repobee.exception.UnexpectedException: a IndexError occured unexpectedly: list index out of range
```

`verify-settings` correctly identifies the problem, but the crash shouldn't occur like this.

**Comment by slarse** [comment]
It should rather raise a `repobee_plug.APIError`
