### ISSUE TITLE
Crashes at initial state after activating junit4 plugin

### ISSUE THREAD

**Issue by GlennOlsson** [repobee/repobee#761]
Reinstalled the junit4 plugin to upgrade it and whenever I try to run repobee, with any command, I get this stack trace
```
[ERROR] Plugin 'junit4' does not allow 'reference_tests_dir' to be configured
exception was raised before pre-initialization was complete. This is usually due to incorrect settings. Try running the `verify-settings` command and see if the problem can be resolved. If all fails, please open an issue at https://github.com/repobee/repobee/issues/new and supply the stack trace below.
[ERROR] Critical exception
Traceback (most recent call last):
  File "/Users/glenn/.repobee/env/lib/python3.8/site-packages/_repobee/main.py", line 166, in _main
    parsed_args, api = _parse_args(
  File "/Users/glenn/.repobee/env/lib/python3.8/site-packages/_repobee/main.py", line 225, in _parse_args
    parsed_args, api = _repobee.cli.parsing.handle_args(
  File "/Users/glenn/.repobee/env/lib/python3.8/site-packages/_repobee/cli/parsing.py", line 56, in handle_args
    args, processing = _parse_args(sys_args, config_file)
  File "/Users/glenn/.repobee/env/lib/python3.8/site-packages/_repobee/cli/parsing.py", line 80, in _parse_args
    parser = cli.mainparser.create_parser(config_file)
  File "/Users/glenn/.repobee/env/lib/python3.8/site-packages/_repobee/cli/mainparser.py", line 131, in create_parser
    _add_subparsers(parser, config_file)
  File "/Users/glenn/.repobee/env/lib/python3.8/site-packages/_repobee/cli/mainparser.py", line 223, in _add_subparsers
    pluginparsers.add_plugin_parsers(
  File "/Users/glenn/.repobee/env/lib/python3.8/site-packages/_repobee/cli/pluginparsers.py", line 37, in add_plugin_parsers
    _attach_command(
  File "/Users/glenn/.repobee/env/lib/python3.8/site-packages/_repobee/cli/pluginparsers.py", line 69, in _attach_command
    cmd.attach_options(config=parsed_config, parser=ext_parser)
  File "/Users/glenn/.repobee/env/lib/python3.8/site-packages/repobee_plug/_pluginmeta.py", line 192, in _attach_options
    raise exceptions.PlugError(
repobee_plug.exceptions.PlugError: Plugin 'junit4' does not allow 'reference_tests_dir' to be configured
[ERROR] A plugin exited with an error
```
This was running just `repobee`

I assume it has to do with a `reference_tests_dir` property in my config but now I cannot even localise the config file, and I don't remember where it is hehe...

**Comment by slarse** [comment]
Right, that's a bit of a hassle, you'll need to remove the config entry manually.

Run the following:

```
$ repobee --no-plugins config show
```

That should show you were the config file is. I'll add this to the [FAQ](https://repobee.readthedocs.io/en/latest/faq.html).

**Comment by slarse** [comment]
@GlennOlsson thanks for reporting this, I've updated the [FAQ](https://repobee.readthedocs.io/en/latest/faq.html).
