### ISSUE TITLE
Not possible to use sub-groups as Organisation name whilst using GitLab plugin

### ISSUE THREAD

**Issue by sakehl** [repobee/repobee#890]
Hi,

We've started using Repobee together with the GitLab plugin. We've set up the first assignment, and this worked perfectly, but now we try to run setup again (since not all students created an account yet the first time), we encountered an error. It seems to be related that we use a Sub-group as the `org_name` in the settings. Since when I do not use a sub-group, but a normal group I don't get errors.

This is the first run, no errors yet:
```
$ repobee repos setup --assignments ha-0 --students-file test-students.txt 
Cloning template repositories: 100%|███████████| 1/1 [00:00<00:00,  3.45repos/s]
Creating student teams: 100%|█████████████████████| 3/3 [00:01<00:00,  1.52it/s]
Setting up student repos: 100%|███████████████████| 3/3 [00:03<00:00,  1.30s/it]
Progress batch 1: 100%|███████████████████████████| 3/3 [00:01<00:00,  2.93it/s]
hook results for ha-0
```
Now the second run (I've added --tb for debugging):
```
$ repobee repos setup --assignments ha-0 --students-file test-students.txt --tb
Cloning template repositories: 100%|███████████| 1/1 [00:00<00:00,  2.84repos/s]
Creating student teams: 100%|█████████████████████| 3/3 [00:00<00:00,  3.26it/s]
Setting up student repos:   0%|                           | 0/3 [00:00<?, ?it/s]
[ERROR] 404: 404 Project Not Found
[ERROR] Critical exception
Traceback (most recent call last):
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/gitlab/exceptions.py", line 279, in wrapped_f
    return f(*args, **kwargs)
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/gitlab/mixins.py", line 214, in create
    server_data = self.gitlab.http_post(path, post_data=data, files=files, **kwargs)
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/gitlab/__init__.py", line 681, in http_post
    result = self.http_request(
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/gitlab/__init__.py", line 572, in http_request
    raise GitlabHttpError(
gitlab.exceptions.GitlabHttpError: 400: {'name': ['has already been taken'], 'path': ['has already been taken'], 'limit_reached': []}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/_repobee/ext/gitlab.py", line 70, in _try_api_request
    yield
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/_repobee/ext/gitlab.py", line 189, in create_repo
    project = self._gitlab.projects.create(
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/gitlab/exceptions.py", line 281, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
gitlab.exceptions.GitlabCreateError: 400: {'name': ['has already been taken'], 'path': ['has already been taken'], 'limit_reached': []}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/_repobee/command/repos.py", line 246, in _create_or_fetch_repo
    api.create_repo(
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/_repobee/ext/gitlab.py", line 198, in create_repo
    return self._wrap_project(project)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/_repobee/ext/gitlab.py", line 83, in _try_api_request
    raise plug.PlatformError(str(e), status=e.response_code) from e
repobee_plug.exceptions.PlatformError: 400: {'name': ['has already been taken'], 'path': ['has already been taken'], 'limit_reached': []}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/gitlab/exceptions.py", line 279, in wrapped_f
    return f(*args, **kwargs)
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/gitlab/mixins.py", line 50, in get
    server_data = self.gitlab.http_get(path, **kwargs)
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/gitlab/__init__.py", line 599, in http_get
    result = self.http_request(
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/gitlab/__init__.py", line 572, in http_request
    raise GitlabHttpError(
gitlab.exceptions.GitlabHttpError: 404: 404 Project Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/_repobee/ext/gitlab.py", line 70, in _try_api_request
    yield
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/_repobee/ext/gitlab.py", line 213, in get_repo
    project = self._gitlab.projects.get("/".join(path))
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/gitlab/exceptions.py", line 281, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
gitlab.exceptions.GitlabGetError: 404: 404 Project Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/_repobee/main.py", line 171, in _main
    _repobee.cli.dispatch.dispatch_command(
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/_repobee/cli/dispatch.py", line 56, in dispatch_command
    dispatch_table[category](args, config_file, api) or hook_results
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/_repobee/cli/dispatch.py", line 80, in _dispatch_repos_command
    return command.setup_student_repos(
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/_repobee/command/repos.py", line 85, in setup_student_repos
    to_push, preexisting = _create_state_separated_push_tuples(
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/_repobee/command/repos.py", line 192, in _create_state_separated_push_tuples
    for created, pt in push_tuple_iter_progress:
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/_repobee/command/repos.py", line 220, in _create_push_tuples
    created, repo = _create_or_fetch_repo(
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/_repobee/command/repos.py", line 252, in _create_or_fetch_repo
    repo = api.get_repo(repo_name=name, team_name=team_name)
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/_repobee/ext/gitlab.py", line 214, in get_repo
    return self._wrap_project(project)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/_repobee/ext/gitlab.py", line 76, in _try_api_request
    raise plug.NotFoundError(str(e), status=404) from e
repobee_plug.exceptions.NotFoundError: 404: 404 Project Not Found
[ERROR] A plugin exited with an error
```

The settings that produce this error look something like:
```
[repobee]
base_url = https://gitlab.mysite.com
user = 20194647
token = _--random token I edited away--_
template_org_name = course-name/assignments
org_name = course-name/2020-2021
```

I hope this is clear, and you can help us out! Thanks in advance

**Comment by sakehl** [comment]
I've dived into this since I really wanted this to work (and not create the repo's again). Seems like an easy fix, works on my end now.

**Comment by slarse** [comment]
Hi @sakehl,

I'm sorry you've run into trouble, but massive thanks for the thorough bug report and PR. I'll have a closer look at this after work today.
