### ISSUE TITLE
Usernames in Gitlab are case insensative

### ISSUE THREAD

**Issue by sakehl** [repobee/repobee#900]
Hi,

I'm unsure if this should be fixed or not, but it is a bit annoying. Apparently, user names in Gitlab are case insensitive, see [here](https://gitlab.com/gitlab-org/gitlab-foss/-/issues/38304):

> But usernames are unique in a case-insensitive manner, see [User model](https://gitlab.com/gitlab-org/gitlab-ce/blob/313fbd5f74c202c3a6f003a39f5ffcf583045d07/app/models/user.rb#L151). So I guess we could modify UsersFinder to make it search case-insensitive.

 Thus, for instance, the real username as is stored in GitLab is "TestUser". But you configured this user as "testuser" in your students file.

Now if you run
```repobee repos setup --tb```
with this student file, I'll get an error like:
<details>
<summary> click for details </summary>

```
[ERROR] 409: Member already exists
[ERROR] Critical exception
Traceback (most recent call last):
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/gitlab/exceptions.py", line 279, in wrapped_f
    return f(*args, **kwargs)
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/gitlab/mixins.py", line 214, in create
    server_data = self.gitlab.http_post(path, post_data=data, files=files, **kwargs)
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/gitlab/__init__.py", line 676, in http_post
    result = self.http_request(
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/gitlab/__init__.py", line 567, in http_request
    raise GitlabHttpError(
gitlab.exceptions.GitlabHttpError: 409: Member already exists

 

The above exception was the direct cause of the following exception:

 

Traceback (most recent call last):
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/_repobee/ext/gitlab.py", line 80, in _try_api_request
    yield
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/_repobee/ext/gitlab.py", line 178, in assign_members
    group.members.create(
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/gitlab/exceptions.py", line 281, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
gitlab.exceptions.GitlabCreateError: 409: Member already exists

 

The above exception was the direct cause of the following exception:

 

Traceback (most recent call last):
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/_repobee/main.py", line 174, in _main
    _repobee.cli.dispatch.dispatch_command(
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/_repobee/cli/dispatch.py", line 56, in dispatch_command
    dispatch_table[category](args, config_file, api) or hook_results
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/_repobee/cli/dispatch.py", line 80, in _dispatch_repos_command
    return command.setup_student_repos(
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/_repobee/command/repos.py", line 83, in setup_student_repos
    platform_teams = _create_platform_teams(teams, api)
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/_repobee/command/repos.py", line 115, in _create_platform_teams
    return list(
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/_repobee/command/teams.py", line 33, in create_teams
    api.assign_members(team, new_members, permission)
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/_repobee/ext/gitlab.py", line 178, in assign_members
    group.members.create(
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/lars/.repobee/env/lib/python3.8/site-packages/_repobee/ext/gitlab.py", line 93, in _try_api_request
    raise plug.PlatformError(str(e), status=e.response_code) from e
repobee_plug.exceptions.PlatformError: 409: Member already exists
[ERROR] A plugin exited with an error
```
</details>

I can ultimately trace this back to the "create_teams" function in the `command/teams.py` file.

In line 32, it says something like:
```python
existing_members = set(team.members)
new_members = set(required_team.members) - existing_members
```
It will go to this team, try to add a new member, although there is already an existing member. (but will not filter it out with the set, since that is case sensitive).

We could fix this by doing this:
```python
existing_members = {t.lower() for t in team.members}
required_members = {t.lower() for t in required_team.members}
new_members = required_members - existing_members
```

But I am not 100% sure if github ([here](https://happygitwithr.com/github-acct.html) it says it is) or gittea or whatever is also username case insensitive. Maybe you can give your thoughts.

**Comment by slarse** [comment]
This is a bug. I'm almost certain all of these platforms have case-insensitive usernames as the usernames are always used for the URL to the user's profile (and URLs are for all reasonable routing implementations, case insensitive). Case sensitive usernames seems like a monumentally bad idea, so I really do not think any of the platforms support it, but I'll double check.

At the very least, both GitHub and GitLab are case insensitive, so this is a bug for the major platforms and needs to be fixed. I'll see to this over the weekend.

**Comment by slarse** [comment]
And thanks for the bug report!

**Comment by sakehl** [comment]
A similar issue happens when you have a students team already setup, but it has a different case compared to what the student is called.

So suppose again you have a team named "TestStudent", but the students is configured as "teststudent"
We will get:
```
[ERROR] PlatformError: 400: Failed to save group {:path=>["has already been taken"]}
[ERROR] A plugin exited with an error
```

We can then again fix this in changing in https://github.com/repobee/repobee/blob/master/src/_repobee/ext/gitlab.py#L156 
```python
if not team_names or group.path.lower() in unique_team_names
```
And in https://github.com/repobee/repobee/blob/master/src/_repobee/command/teams.py#L21-L30
```python
    existing_teams_dict = {
        existing.name.lower(): existing
        for existing in api.get_teams({t.name.lower() for t in teams})
    }
    for required_team in teams:
        team = existing_teams_dict.get(required_team.name.lower()) or api.create_team(
            required_team.name,
            members=required_team.members,
            permission=permission,
        )
```

probably this needs to be applied for github and gittea as well.

**Comment by slarse** [comment]
The `path` thing for GitLab will of course need to be separately handled, but the fixes I've outlined above should resolve the problems on all other platforms.

**Comment by sakehl** [comment]
Thanks a lot!

**Comment by slarse** [comment]
You're welcome! Do check if it solves the problem for you. I'm pretty confident that it should, as both crashes you provided were reproducible in the system tests.

See #903 as well; I think this affects more parts than just usernames.
